# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20170809_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='my_date',
        ),
    ]
